version: "3"
services:
  web:
    build: ./Result/Result
    expose:
        - "80"
    depends_on:
        - db
    labels:
        - "SERVICE_NAME=Result"
        - "SERVICE_TAGS=ResultTag"
  db:
     image: "mongo:latest"
     restart: always
