version: "3"
services:
  web:
    build: ./Result/Result/
    depends_on:
        - db
    expose:
        - "80"
    labels:
      - "SERVICE_NAME=Result"
      - "SERVICE_TAGS=ResultTag"
  db:
    image: "mongo:latest"